DATA SEGMENT
    NUM DW 019,
    SQUARE DW 3 DUP<0>
    DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE,DS:DATA
    START:MOV AX,DATA
    MOV DS,AX
    LEA SI,NUM       ;POINT SI TO NUM
    MOV AX,[SI]      ;MOVE THE VALUE STORED IN SI TO AX
    MUL AX           ;MULTIPLY AX WITH AX
    MOV SQUARE,AX    ;MOVE THE RESULT TO SQUARE
    MOV AH,4CH
    INT 21H
    CODE ENDS
END START
